steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
  # us-central1-docker.pkg.dev/gleaming-vision-397409/python-repo
  # 'us-central1-docker.pkg.dev/pub-demo-cb-ar/python-repo/my-app:${SHORT_SHA}',
  # 'us-central1-docker.pkg.dev/pub-demo-cb-ar/python-repo/my-app:latest',
  # 'us-central1-docker.pkg.dev/pub-demo-cb-ar/python-repo/my-app:latest',
    args: [
            'build',
            '-t',
            'us-central1-docker.pkg.dev/gleaming-vision-397409/python-repo/my-app:${SHORT_SHA}',
            '-t',
            'us-central1-docker.pkg.dev/gleaming-vision-397409/python-repo/my-app:latest',
            '--cache-from',
            'us-central1-docker.pkg.dev/gleaming-vision-397409/python-repo/my-app:latest',
            '.'
          ]

  # Docker push to Google Artifact Registry
  # args: ['push',  'us-central1-docker.pkg.dev/pub-demo-cb-ar/python-repo/my-app:${SHORT_SHA}']
  #
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/gleaming-vision-397409/python-repo/my-app:${SHORT_SHA}']

# Store images in Google Artifact Registry
#- us-central1-docker.pkg.dev/pub-demo-cb-ar/python-repo/my-app:${SHORT_SHA}
#  - us-central1-docker.pkg.dev/pub-demo-cb-ar/python-repo/my-app:latest
images:
  - us-central1-docker.pkg.dev/gleaming-vision-397409/python-repo/my-app:${SHORT_SHA}
  - us-central1-docker.pkg.dev/gleaming-vision-397409/python-repo/my-app:latest
